version: '3.3'

services:

  wordpress:
    build:
      context: ./docker
      dockerfile: Dockerfile-wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('SCRIPT_DEBUG', true );
        define('BETTEREMBED_DEBUG', true );
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/betterembed
    depends_on:
      - db
    command: bash /var/www/html/wp-content/plugins/betterembed/docker/docker-entrypoint.sh

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - /sessions
    environment:
      - PMA_HOST=db
      - PMA_USER=wp
      - PMA_PASSWORD=wp

  wp:
    build:
      context: ./docker
      dockerfile: Dockerfile-wp
    # https://github.com/docker-library/docs/tree/master/wordpress#running-as-an-arbitrary-user
    user: "33:33"
    working_dir: /var/www/html/wp-content/plugins/betterembed
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/betterembed
    depends_on:
      - wordpress
      - db

  scripts:
    image: node:13
    user: 1000:1000
    working_dir: /usr/var/app
    volumes:
      - .:/usr/var/app/
    command: npm start

  composer:
    image: composer
    user: 1000:1000
    volumes:
      - .:/app

  tests:
    image: php:7.4-cli
    user: 1000:1000
    working_dir: /usr/var/app
    volumes:
      - .:/usr/var/app
    command: [ "./vendor/bin/phpunit", "tests" ]

volumes:
  wordpress:
  db:
